### ISSUE TITLE
Add support for scheduling

### ISSUE THREAD

**Issue by cadamsdev** [cadamsdev/image-optimizer-action#9]
We should be able to add a cronjob to the workflow file

e.g
```
on:
  workflow_dispatch: # Retains manual trigger
  schedule:
    # For daily runs at midnight UTC, use:
    - cron: '0 0 * * *'
    # For weekly runs (e.g., every Sunday at midnight UTC), use:
    # - cron: '0 0 * * 0'
```

COA
- Update the github action to support schedule events
- Update the README to show an example for scheduling
